Update pipelines from RC

diff --git a/.github/workflows/getunityversionfrompackage.yml b/.github/workflows/getunityversionfrompackage.yml
--- a/.github/workflows/getunityversionfrompackage.yml
+++ b/.github/workflows/getunityversionfrompackage.yml
@@ -51,6 +51,12 @@ jobs:
           $package_json = Get-Content -Path $versionFile | ConvertFrom-Json
           $unityVersion = $package_json.unity
 
+          if($unityVersion.Length -lt 6) {
+            echo "Error - Detected version is $unityVersion"
+            echo "Unity version is too short, please check your UPM package Unity setting"
+            exit 1
+          }
+
           echo "Detected version is $unityVersion"
           echo "::set-output name=upmunityversion::$unityVersion"
           echo "::endgroup::"
diff --git a/.github/workflows/rununityunittests.yml b/.github/workflows/rununityunittests.yml
--- a/.github/workflows/rununityunittests.yml
+++ b/.github/workflows/rununityunittests.yml
@@ -143,6 +143,13 @@ jobs:
             # Read dependancy input value
             $dependencies = '${{ inputs.dependencies }}'
 
+            if([string]::IsNullOrEmpty('${{ secrets.GIT_USER_NAME }}') -or [string]::IsNullOrEmpty('${{ secrets.GIT_PAT }}')){
+              echo ""
+              echo "Secrets for GIT_USER_NAME or GIT_PAT missing, please register them with access to this runner"
+              echo "*Note, Organisation secrets are not accessible to Forked repos and need registering in the local fork"
+              exit 1
+            }
+
             # Read dependancy input values as json
             $JSONdependencies = $dependencies | ConvertFrom-Json
 
@@ -153,37 +160,49 @@ jobs:
             $strArray = $projectManifest.dependencies.PsObject.Properties | ForEach-Object {"$($_.Name)@$($_.Value),"}
 
             # Loop through new dependancies and add them to the project Manifest
-            $JSONdependencies.PsObject.Properties | ForEach-Object -Process { 
-              $dependencyName = $_.Name
-              $dependencyURL = $_.Value
+            foreach($dependency in $JSONdependencies){
+              $dependency.PsObject.Properties | ForEach-Object -Process { 
+                $dependencyName = $_.Name
+                $dependencyURL = $_.Value
+                $cloneURL = "https://${{ secrets.GIT_USER_NAME }}:${{ secrets.GIT_PAT }}@$dependencyURL"
 
-              echo "cloning $dependencyName from $dependencyURL and moving to $destinationPath"
+                echo "cloning $dependencyName from $dependencyURL and moving to $destinationPath"
+                echo "git path - $cloneURL"
 
-              # Clone Dependancy repo to destination folder
-              git clone -b $dependencyName --single-branch "https://${{ secrets.GIT_USER_NAME }}:${{ secrets.GIT_PAT }}@$dependencyURL" $dependencyName
+                # Clone Dependancy repo to destination folder
+                git clone -b $dependencyName --single-branch $cloneURL $dependencyName
 
-              if( -not (Test-Path -Path "$dependencyName")){
-                echo "Unable to clone $dependencyName from $dependencyURL"
-                exit 1
+                if( -not (Test-Path -Path "$dependencyName")){
+                  echo "Unable to clone $dependencyName from $dependencyURL"
+                  exit 1
+                }
+
+                # Move files from clone path into packages folder, if the dependency contains a UPM package then move the entire folder and not just its contents
+                if (Test-Path -Path "$dependencyName/package.json") {
+                  $package_json = Get-Content -Path $dependencyName/package.json | ConvertFrom-Json
+                  $packageName = $package_json.name
+                  Rename-Item $dependencyName $packageName
+                  echo "Moving whole $packageName UPM package to $destinationPath"
+                  Move-Item -Path "$packageName" -Destination $destinationPath
+                }
+                else {
+                  echo "Moving the contents of $dependencyName into the $destinationPath folder"
+                  Move-Item -Path "$dependencyName/*" -Destination $destinationPath
+                }
+
+                # Get Dependency manifest entries (if applicable)
+                if (Test-Path -Path "$destinationPath/$dependencyName.json") {
+                    $dependencyManifest = Get-Content -Path "$destinationPath/$dependencyName.json" | ConvertFrom-Json
+                    $dependencyManifest.dependencies.PsObject.Properties | ForEach-Object {
+                        $strArray += "$($_.Name)@$($_.Value),"
+                    }
+                }
+                else{
+                  echo "No denendency json found called $destinationPath/$dependencyName.json, skipping adding additional manifest entries"
+                }
               }
-
-              # Move files from clone path in to packages folder
-
-              Move-Item -Path "$dependencyName/*" -Destination $destinationPath
-
-              # Get Dependency manifest entries (if applicable)
-              if (Test-Path -Path "$destinationPath/$dependencyName.json") {
-                  $dependencyManifest = Get-Content -Path "$destinationPath/$dependencyName.json" | ConvertFrom-Json
-                  $dependencyManifest.dependencies.PsObject.Properties | ForEach-Object {
-                      $strArray += "$($_.Name)@$($_.Value),"
-                  }
-              }
-              else{
-                echo "No denendency json found called $destinationPath/$dependencyName.json, skipping adding additional manifest entries"
-              }
-
             }
-
+            
             # Reformat combined dependancies list
             $strArray = $strArray.Trim(",") | ConvertTo-Json 
             $strArray = $strArray.Replace("@",'":"').Replace("[","{").Replace("]","}")
