Try $LASTEXITCODE

diff --git a/.github/workflows/rununityunittests.yml b/.github/workflows/rununityunittests.yml
--- a/.github/workflows/rununityunittests.yml
+++ b/.github/workflows/rununityunittests.yml
@@ -223,10 +223,10 @@ jobs:
 
           # Start Testing
           $testResult = unity-editor -runEditorTests -projectPath $TempUnityProjectName -logfile $logPath -editorTestsResultFile $testsLogPath -buildTarget ${{ matrix.build-target }}
-          if($testResult.ExitCode -ne '0'){
+          if($LASTEXITCODE -ne '0'){
             $exitCode = $testResult.ExitCode
-            echo "Build failed due to errors ($exitCode), please check the log at $logPath"
-            exit $testResult.ExitCode
+            echo "Build failed due to errors ($LASTEXITCODE), please check the log at $logPath"
+            exit $LASTEXITCODE
           }
           echo "::endgroup::"
 
